timestamp = 2022-09-26T04:11:52Z
url = 'https://github.com/input-output-hk/cardano-ledger/tarball/b60030adefd7e9eedd0f59b9ed99161894c3fdcb'
subdir = './libs/cardano-ledger-pretty'
force-version = true
