timestamp = 2022-09-22T11:29:02Z
url = 'https://github.com/input-output-hk/ouroboros-network/tarball/2146e721a58c0cce241f6e53485d883531764775'
subdir = './ouroboros-network-testing'
force-version = true
