timestamp = 2022-09-23T04:42:00Z
url = 'https://github.com/input-output-hk/ouroboros-network/tarball/473b5db02d0541ed1a84d4413f19a30e0536d6f0'
subdir = './ouroboros-consensus/docs/report/unsoundswitch'
force-version = true
