timestamp = 2022-09-19T05:23:20Z
url = 'https://github.com/input-output-hk/ouroboros-network/tarball/f23de88f53fbf263a9f13564e27987dd9e4f2f6a'
subdir = './ouroboros-consensus-protocol'
force-version = true
