timestamp = 2022-09-19T04:38:28Z
url = 'https://github.com/input-output-hk/ouroboros-network/tarball/b3d225e96a163347cf6c5182a834c89499363bd9'
subdir = './ouroboros-consensus-byron-test'
force-version = true
